version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc_search_web
    ports:
      - 8000:80
    volumes:
      - .:/app
      - log:/app/log
    restart: always
    working_dir: /app
    command: > 
      bash -c "
        service nginx restart &&
        uwsgi --ini infra_conf/uwsgi.ini"
volumes:
  log: